Dashboard resolver
NKisiura/te-frontend-rework pull request #13
Opened 2023-07-14 10:37 UTC by NKisiura

2023-07-14 12:55 UTC, LeonidShubin requested changes

2023-07-14 12:55 UTC, LeonidShubin commented on src/app/app.component.ts
> +    this.router.events.subscribe(event => {
відписатися

2023-07-14 12:55 UTC, LeonidShubin commented on src/app/global/guards/permission.guard.ts
> +  const resources: string[] = route.data['resources'] || [];
перейменувати на перміти

2023-07-14 12:55 UTC, LeonidShubin commented on src/app/global/guards/permission.guard.ts
> +    tap(isLoaded => {
перевірити чи потрібно запитувати готовність для чайлд роутів

2023-07-15 11:03 UTC, NKisiura commented on src/app/global/guards/permission.guard.ts
> +    tap(isLoaded => {
Для чайлд роутів потрібно запитувати, резолвер на парент роурі відпрацює тільки коли редірект сама на цей роут з резолвером, якщо перезавантажити сторінку на його чайлд роутах, він не спрацює, що як на мене вері конфьюзінг.

2023-07-15 18:48 UTC, merged